
language: python
python:
  - 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov


script:
  - flake8
  - coverage run -m pytest 

after_success:
  - codecov
branches:
  only:
  - master
